[package]
name = "teamprojekt-docker-access"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
tar = "0.4"
serde = "1.0"
serde_json = "1.0"
regex = "1.11.1"